### ISSUE TITLE
Wrong naming on Azure resources

### ISSUE THREAD

**Issue by jjindrich** [azurecz/azuretechacademy-hybridit-labs-day2#1]
@tkubica12 change names of resources and resource groups to recommended naming conventions. 
Use company prefix, e.g. cp

arm-spoke2-networking -> cp-spoke2-networking-rg
spoke2-net -> cp-spoke2-vnet

**Comment by jjindrich** [comment]
Ideally add network schema you are trying to create it

**Comment by tkubica12** [comment]
make sense, will fix that

**Comment by tkubica12** [comment]
Fixed with ccc5dbb
